version: "3.9"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/app.env
