version: "3.8"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - app-server-1
      - app-server-2
  app-server-1:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/app.env
    depends_on:
      - db-mysql
  app-server-2:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/app.env
    depends_on:
      - db-mysql
  migration:
    build:
      context: ./flyway
      dockerfile: Dockerfile
    environment:
      FLYWAY_EDITION: community
    volumes:
      - ${PWD}/flyway/db-migration:/flyway/sql
      - ${PWD}/flyway/conf:/flyway/conf
    depends_on:
      - db-mysql
  db-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - env/mysql.env
