version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf/:/etc/nginx/conf.d/"
    depends_on:
      - dongne-api
  dongne-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - env/app.env
    depends_on:
      - db
  db:
    image: mysql:5.7.34
    ports:
      - "3306:3306"
    env_file:
      - env/db.env
