version: "3.9"
services:
  db:
    image: mysql:8.0.32
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dongne
      - MYSQL_ROOT_PASSWORD=beaniejoy
  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
