version: "3.8"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - app-server-1
      - app-server-2
  app-server-1:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/app.env
    depends_on:
      - db-mysql
  app-server-2:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/app.env
    depends_on:
      - db-mysql
  migration:
    image: flyway/flyway:7.5.1
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/flyway/db-migration/main:/flyway/sql
      - ${PWD}/flyway/conf/flyway_main.conf:/flyway/conf/flyway.config
    depends_on:
      - db-mysql
  seed:
    image: flyway/flyway:7.5.1
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/flyway/db-migration/seed:/flyway/sql
      - ${PWD}/flyway/conf/flyway_seed.conf:/flyway/conf/flyway.config
    depends_on:
      - db-mysql
  db-mysql:
    image: mysql:5.7.34
    ports:
      - "3306:3306"
    env_file:
      - env/mysql.env
