version: "3.9"
services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - env/app.env
networks:
  default:
    external:
      name: api-net