- name: "[Rolling Update] Shutdown old application - {{ item }}"
  ansible.builtin.command: "{{ remote_app_path }}/service.sh shutdown {{ item }}"
  register: result
  become: false

- ansible.builtin.debug:
    msg: "{{ result.stdout_lines }}"

- name: "[Rolling Update] Run service script - {{ item }}"
  ansible.builtin.command: "{{ remote_app_path }}/service.sh run {{ item }}"
  register: result
  become: false
  environment:
    VAULT_DOMAIN_ADDR: "{{ vault_address }}"
    VAULT_AUTH_TOKEN: "{{ vault_token }}"

- ansible.builtin.debug:
    msg: "{{ result.stdout_lines }}"
