spring:
  redis:
    host: localhost
    port: 6379
    password:
    connect-timeout: 3000
    timeout: 3000
    database: 0
    lettuce:
      pool:
        max-active: 3
        max-idle: 3
        min-idle: 3
        max-wait: 3
