spring:
  config:
    import: optional:file:${ENV_LOCATION}/.env[.properties]
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://${DATABASE_HOST}/dongne
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      maximum-pool-size: 5
      minimum-idle: 5
jwt:
  secret_key: ${SECRET_KEY}
  validity_time_in_sec: ${SECRET_KEY_VALIDITY_TIME}