---
- name: Test Playbook
  hosts: ec2

  vars_files:
    - vars/all.yml
    - "{{ jenkins_user_home }}/ansible/vars/app_config.yml"

  tasks:
    - name: Register JAR file existence status
      ansible.builtin.stat:
        path: "{{ remote_workspace }}/deploy/{{ module_name }}.jar"
      register: file_status

    - name: Check if JAR file exists
      block:
        - name: Check 'file_status'
          ansible.builtin.fail:
            msg: "{{ module_name }}.jar does not exist"
          when: not file_status.stat.exists

        - name: Print success message
          ansible.builtin.debug:
            msg: "{{ module_name }}.jar exists!!"

    - name: Copy JAR file for running application
      ansible.builtin.copy:
        src: "{{ remote_workspace }}/deploy/{{ module_name }}.jar"
        remote_src: yes
        dest: "{{ remote_workspace }}/app/{{ module_name }}.jar"
        owner: "{{ remote_server_user }}"
        group: "{{ remote_server_group }}"
        mode: 0644

    - name: Copy env file to remote server
      ansible.builtin.template:
        src: ./templates/.env.j2
        dest: "{{ remote_workspace }}/app/env/.env"
        owner: "{{ remote_server_user }}"
        group: "{{ remote_server_group }}"
        mode: 0644

#    - name: Export env file location variable
#      ansible.builtin.command: "export ENV_LOCATION={{ remote_workspace }}/app"

    - name: Remove deployed JAR file
      ansible.builtin.file:
        state: absent
        path: "{{ remote_workspace }}/deploy/{{ module_name }}.jar"

    - name: Finish
      ansible.builtin.debug:
        msg: "All tasks completed!!"