spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://${DATABASE_HOST}/dongne
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      maximum-pool-size: 5
      minimum-idle: 5
