spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://${DATABASE_HOST}/dongne
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      maximum-pool-size: 5
      minimum-idle: 5

logging:
  level:
    org.hibernate.SQL: info # logger 통해 로깅
    org.hibernate.type: trace