spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dongne?autoreconnect=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: beaniejoy # TODO 추후 보안에 대해 생각해보기
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none # flyway migration 사용
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show-sql: false
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/seed
#    baseline-version: 0

logging:
  level:
    org.hibernate.SQL: debug # logger 통해 로깅
#    org.hibernate.type: trace
