- name: "[Blue Green] Copy {{ item }} file to remote server"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ remote_app_path }}/"
    owner: "{{ remote_server_user[ansible_distribution] }}"
    group: "{{ remote_server_group[ansible_distribution] }}"
    mode: 0644
