- name: "[Blue Green] Init group files"
  ansible.builtin.include_tasks:
    file: file_check.yml
    apply:
      tags:
        - blue_green_init
  loop:
    - BLUE
    - GREEN
  tags:
    - blue_green_init

- name: "[Blue Green] Copy service script file to remote server"
  ansible.builtin.template:
    src: blue-green-deploy.sh.j2
    dest: "{{ remote_app_path }}/service.sh"
    owner: "{{ remote_server_user[ansible_distribution] }}"
    group: "{{ remote_server_group[ansible_distribution] }}"
    mode: 0755
  tags:
    - blue_green
    - blue_green_init

- name: "[Blue Green] Run service script"
  ansible.builtin.include_tasks:
    file: deploy.yml
    apply:
      tags:
        - blue_green
        - blue_green_init
  tags:
    - blue_green
    - blue_green_init
