- name: "[Blue Green] Check group files"
  block:
    - name: "Register {{ item }} file"
      ansible.builtin.stat:
        path: "{{ remote_app_path }}/{{ item }}"
      register: group_file

    - name: Fail and print message
      ansible.builtin.fail:
        msg: "{{ item }} does not exist"
      when: not group_file.stat.exists

    - name: Print success message
      ansible.builtin.debug:
        msg: "{{ item }} exists!!"
