# remote server
remote_server_user:
  Amazon: ec2-user
  Debian: pi
remote_server_group:
  Amazon: ec2-user
  Debian: pi
remote_user_workspace: "/home/{{ remote_server_user[ansible_distribution] }}"

remote_deploy_path: "{{ remote_user_workspace }}/deploy"
remote_app_path: "{{ remote_user_workspace }}/app"
remote_app_log_path: "{{ remote_user_workspace }}/app/logs"
remote_app_env_path: "{{ remote_user_workspace }}/app/env"
