---
- name: Install java
  ansible.builtin.dnf:
    name: "{{ java_package }}"
    state: present
  tags:
    - init

- name: Install nginx
  ansible.builtin.dnf:
    name: "{{ nginx_package }}"
    state: present
  tags:
    - init

- name: System details
  debug: msg="{{ item }}"
  with_items:
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
  tags:
    - test
