spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false

logging:
  level:
    org.hibernate.SQL: debug # ionShutdownHook logging issue (in 'DEBUG' level)
    org.hibernate.type: trace # 실제 sql 쿼리의 parameter 값을 확인하고자 함