spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/dongne?autoreconnect=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
      username: root
      password: beaniejoy
      maximum-pool-size: 5
      minimum-idle: 5

logging:
  level:
    org.hibernate.SQL: debug # logger 통해 로깅
#    org.hibernate.type: trace