spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s # default 30s (graceful shutdown)

  datasource:
    hikari:
      connection-timeout: 3000
      validation-timeout: 1000
      max-lifetime: 1800000 # 30 minutes (default)
      data-source-properties: # 성능 테스트 필요
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show-sql: false
    open-in-view: false

  data:
    jpa:
      repositories:
        enabled: false

server:
  shutdown: graceful
