spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s # default 30s (graceful shutdown)

  datasource:
    hikari:
      connection-timeout: 3000
      validation-timeout: 1000
      max-lifetime: 1800000 # 30 minutes (default)
      data-source-properties: # 성능 테스트 필요
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show-sql: false
    open-in-view: false

  config:
    import:
      - optional:vault://
      - optional:file:./env/.env[.properties] # local
  cloud:
    vault:
      uri: ${VAULT_DOMAIN_ADDR} # vault domain uri (port: 8200)
      authentication: TOKEN
      token: ${VAULT_AUTH_TOKEN} # vault root token
      connection-timeout: 3000
      read-timeout: 10000
      kv:
        backend: secret
        application-name: dongne
        default-context:
        profiles: ${spring.profiles.active}

server:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: test

  cloud:
    vault:
      enabled: false
