# actuator
management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: "health"

  endpoint:
    info:
      enabled: true
    health:
      enabled: true
