---
- name: "Make directory({{ remote_app_path }})"
  ansible.builtin.file:
    path: "{{ remote_app_path }}"
    state: directory
    owner: "{{ remote_server_user[ansible_distribution] }}"
    group: "{{ remote_server_group[ansible_distribution] }}"
    mode: 0755
  tags:
    - init
    - setup

- name: "Make directory({{ remote_app_log_path }})"
  ansible.builtin.file:
    path: "{{ remote_app_log_path }}"
    state: directory
    mode: 0755
    owner: "{{ remote_server_user[ansible_distribution] }}"
    group: "{{ remote_server_group[ansible_distribution] }}"
  tags:
    - init
    - setup

- name: "Make directory({{ remote_app_env_path }})"
  ansible.builtin.file:
    path: "{{ remote_app_env_path }}"
    state: directory
    mode: 0755
    owner: "{{ remote_server_user[ansible_distribution] }}"
    group: "{{ remote_server_group[ansible_distribution] }}"
  tags:
    - init
    - setup
